apiVersion: apps/v1
kind: Deployment
metadata:
  name: &app nginx-globe-gl
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: *app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: *app
    spec:
      containers:
      - name: *app
        image: devbytom/nginx-globe-gl
        ports:
        - containerPort: &port 9999
          protocol: tcp
        livenessProbe:
          httpGet:
            path: /healthz
            port: *port
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz
            port: *port
          initialDelaySeconds: 10
          periodSeconds: 60
        env:
        - name: SELF_URL
          valueFrom:
            secretKeyRef:
              name: nginx-globe-gl
              key: SELF_URL
        - name: ELASTICSEARCH_HOST
          valueFrom:
            secretKeyRef:
              name: nginx-globe-gl
              key: ELASTICSEARCH_HOST
        - name: ELASTICSEARCH_USER
          valueFrom:
            secretKeyRef:
              name: nginx-globe-gl
              key: ELASTICSEARCH_USER
        - name: ELASTICSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nginx-globe-gl
              key: ELASTICSEARCH_PASSWORD
        - name: ELASTICSEARCH_QUERY
          valueFrom:
            secretKeyRef:
              name: nginx-globe-gl
              key: ELASTICSEARCH_QUERY
