apiVersion: v1
kind: Service
metadata:
  name: &app nginx-globe-gl
spec:
  type: ClusterIP
  selectors:
    app.kubernetes.io/name: *app
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 9999
